import Navigation from "./components/navigation";
import Header from "./components/header";
import "style/global.scss";
import styles from "style/layout.module.scss";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        <div className={styles.pages}>{children}</div>
        <Navigation />
      </body>
    </html>
  );
}
